# Generated by Django 6.0.2 on 2026-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_request_approver_step1_request_approver_step2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
